### ISSUE TITLE
download backup is gone now

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-terminal#112] opened 2017-02-09 10:38 UTC
<img width="695" alt="screen shot 2017-02-09 at 11 36 27" src="https://cloud.githubusercontent.com/assets/9036081/22779727/35d22e0e-eebc-11e6-8bdd-747360f1061b.png">

**Comment by faffydee** [comment] 2017-02-09 12:22
This is something for @sponnet : the check is just done on "is this safari or isn't it?", that's why you don't see the button on safari. Can we specify the check more like "are you on an ios-device?" or something? We need to check if you are using an iPhone/iPad, basically

**Comment by sponnet** [comment] 2017-02-09 15:31
On safari , the download just doesn't work. So it is indeed not a ios/non-ios check , but a check if you use safari.
I would close this , as this is not a bug, it is Safari specific. That is why safari offers the IPFS backup method. Faffy : you either comment or close this please ? TWBG.

**Closed as completed** 2017-02-09 16:11 UTC
